### ISSUE TITLE
你好，我做压测4000并发的时候，报错如下,请问怎么解决

### ISSUE THREAD

**Issue by pengyongjianpyj** [YeautyYE/netty-websocket-spring-boot-starter#110]
i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail
of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:143)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by pengyongjianpyj** [comment]
[development@VM_0_7_centos ~]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 256971
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 100001
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 256971
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by YeautyYE** [comment]
服务端报错还是客户端报错

**Comment by pengyongjianpyj** [comment]
服务端

**Comment by pengyongjianpyj** [comment]
> 服务端报错还是客户端报错

服务端

**Comment by pengyongjianpyj** [comment]
> 服务端报错还是客户端报错

是服务端系统配置有问题吗？

**Comment by YeautyYE** [comment]
> > 服务端报错还是客户端报错
> 
> 是服务端系统配置有问题吗？

从报错来看是打开文件描述符不够大，但是从 ulimit -a来看，又是正常的。
可以查看下，除了连接之外，代码中是否有什么操作会打开文件（linux一切皆文件）

**Comment by pengyongjianpyj** [comment]
PojoMethodMapping这个类的构造方法长度。。。

**Comment by pengyongjianpyj** [comment]
请问除系统文件描述符数量限制外，java进程jvm本身是否也有文件描述数量限制

**Comment by YeautyYE** [comment]
> 请问除系统文件描述符数量限制外，java进程jvm本身是否也有文件描述数量限制

没
