### ISSUE TITLE
启动成功 ,访问socket提示 No adapter for handler [XXXXXNettyWebSocketServer]: The DispatcherServlet configuration needs to include a HandlerAdapter that supports this handler, 请问如何解决?

### ISSUE THREAD

**Issue by Acgnu** [YeautyYE/netty-websocket-spring-boot-starter#131]

**Comment by YeautyYE** [comment]
如果可以的话，把springmvc包去掉就好了

**Comment by Acgnu** [comment]
> 如果可以的话，把springmvc包去掉就好了

这...恐怕不太行, 谢谢XD

**Comment by YeautyYE** [comment]
那要排查下，是否在@ ServerEndpoint 类上面有springmvc的注解，去掉就可以了

**Comment by Acgnu** [comment]
好像还是不行, 可能是我姿势不对, 项目架构spring + mvc + security, 貌似是因为访问的url被security拦截, 读取stream报错, 不过这个url使用javax的socket是在白名单里的, 以下是引用

import io.netty.handler.codec.http.HttpHeaders;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.MultiValueMap;
import org.yeauty.annotation.OnClose;
import org.yeauty.annotation.OnError;
import org.yeauty.annotation.OnMessage;
import org.yeauty.annotation.OnOpen;
import org.yeauty.annotation.PathVariable;
import org.yeauty.annotation.RequestParam;
import org.yeauty.annotation.ServerEndpoint;
import org.yeauty.pojo.Session;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

**Comment by YeautyYE** [comment]
如果可以的话，可以发下代码给我看下

**Comment by Acgnu** [comment]
> 如果可以的话，可以发下代码给我看下

恐怕不行哦, 单独抽出来一个能运行的模块也比较复杂

**Comment by YeautyYE** [comment]
> 恐怕不行哦, 单独抽出来一个能运行的模块也比较复杂
ServerEndpoint 的类发出来也行

**Comment by Acgnu** [comment]
> > 恐怕不行哦, 单独抽出来一个能运行的模块也比较复杂
> > ServerEndpoint 的类发出来也行

链接：https://pan.baidu.com/s/1Hqjyd31-XHLoExnArlt-Uw 
提取码：cdof
抽取出来的最小单元了, 可以代表一个模块的基本框架, 但是这个模块不能直接运行, 只能看代码参考, WebSocketServer.java就是监听类, 辛苦了

**Comment by YeautyYE** [comment]
> 链接：https://pan.baidu.com/s/1Hqjyd31-XHLoExnArlt-Uw
> 提取码：cdof
> 抽取出来的最小单元了, 可以代表一个模块的基本框架, 但是这个模块不能直接运行, 只能看代码参考, WebSocketServer.java就是监听类, 辛苦了

看了一下，问题应该不是出在WebSocketServer.java上，你可以尝试完全把他注释掉，估计还是会报错。
建议排查下各controller上面引入的包是否正确

**Comment by Acgnu** [comment]
> > 链接：https://pan.baidu.com/s/1Hqjyd31-XHLoExnArlt-Uw
> > 提取码：cdof
> > 抽取出来的最小单元了, 可以代表一个模块的基本框架, 但是这个模块不能直接运行, 只能看代码参考, WebSocketServer.java就是监听类, 辛苦了
> 
> 看了一下，问题应该不是出在WebSocketServer.java上，你可以尝试完全把他注释掉，估计还是会报错。
> 建议排查下各controller上面引入的包是否正确

不会呀, 启动包括使用普通的controller访问都没问题, 包括使用javax的socket也没问题, 但是使用这个的话, 启动, 访问别的controller没问题, 访问socket就报错了

**Comment by YeautyYE** [comment]
> 不会呀, 启动包括使用普通的controller访问都没问题, 包括使用javax的socket也没问题, 但是使用这个的话, 启动, 访问别的controller没问题, 访问socket就报错了

没测出这种情况。
你看下是完全把源码发我，还是远程帮你调试看看

**Comment by Acgnu** [comment]
> > 不会呀, 启动包括使用普通的controller访问都没问题, 包括使用javax的socket也没问题, 但是使用这个的话, 启动, 访问别的controller没问题, 访问socket就报错了
> 
> 没测出这种情况。
> 你看下是完全把源码发我，还是远程帮你调试看看

你有空的话我可以开远程给你

**Comment by YeautyYE** [comment]
> 你有空的话我可以开远程给你
要不你加我微信 Yeauty

**Comment by LingzZhiyi** [comment]
我也出现这个问题了。。。有点难受，我自己的

**Comment by YeautyYE** [comment]
> 我也出现这个问题了。。。有点难受，我自己的

可以先将springmvc的包去掉，然后再排查。
应该是引错包了

**Comment by LingzZhiyi** [comment]
> > 我也出现这个问题了。。。有点难受，我自己的
> 
> 可以先将springmvc的包去掉，然后再排查。
> 应该是引错包了

好的，但我这边还是需要mvc，只能另寻他路了

**Comment by YeautyYE** [comment]
> 好的，但我这边还是需要mvc，只能另寻他路了

你可以先去掉mvc的包来排查。
大概率是在websocket中引错包了，把错的去掉就可以将mvc加回来了

**Comment by LingzZhiyi** [comment]
> > 好的，但我这边还是需要mvc，只能另寻他路了
> 
> 你可以先去掉mvc的包来排查。
> 大概率是在websocket中引错包了，把错的去掉就可以将mvc加回来了

mvc排了  起不来，我把websocket排了 试试

**Comment by LingzZhiyi** [comment]
找到问题了，极光推送里面有一个netty 排除就行，还好我这个服务不用极光.
<exclusions>
                <exclusion>
                    <artifactId>netty-all</artifactId>
                    <groupId>io.netty</groupId>
                </exclusion>
            </exclusions>

**Comment by YeautyYE** [comment]
OK

**Comment by poorcharlie** [comment]
我也遇到这个问题了：看样子是springboot内置的tomcat 报错的。请问怎么解决呢



 The DispatcherServlet configuration needs to include a HandlerAdapter that supports this handler
at org.springframework.web.servlet.DispatcherServlet.getHandlerAdapter(DispatcherServlet.java:1233)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by poorcharlie** [comment]
> OK

我也遇到这个问题了：看样子是springboot内置的tomcat 报错的。请问怎么解决呢

The DispatcherServlet configuration needs to include a HandlerAdapter that supports this handler
at org.springframework.web.servlet.DispatcherServlet.getHandlerAdapter(DispatcherServlet.java:1233)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by YeautyYE** [comment]
> > OK
> 
> 我也遇到这个问题了，连接少的时候还正常，一旦压测就报错了，服务器一直刷这个错，重启机器也不行，但是把@serverendpoint 注解去掉又正常了。请问应该怎么解决呢。
> 

1.把springmvc依赖去掉
2.查看@serverendpoint 这个类上面是否import了servlet的包

**Comment by poorcharlie** [comment]
> > > OK
> > 
> > 
> > 我也遇到这个问题了，连接少的时候还正常，一旦压测就报错了，服务器一直刷这个错，重启机器也不行，但是把@serverendpoint 注解去掉又正常了。请问应该怎么解决呢。
> 
> 1.把springmvc依赖去掉
> 2.查看@serverendpoint 这个类上面是否import了servlet的包

嗯嗯，是在spring容器里注入了一个TomcatContextCustomizer 的bean，把这个去掉就不报错了。但是不懂为什么会影响到websocket使用

**Comment by poorcharlie** [comment]
> > > OK
> > 
> > 
> > 我也遇到这个问题了，连接少的时候还正常，一旦压测就报错了，服务器一直刷这个错，重启机器也不行，但是把@serverendpoint 注解去掉又正常了。请问应该怎么解决呢。
> 
> 1.把springmvc依赖去掉
> 2.查看@serverendpoint 这个类上面是否import了servlet的包

是有HttpServletRequest ，但是后来没有用这个类，只剩下 import 没删掉，这样会有直接影响吗

**Comment by YeautyYE** [comment]
> > 1.把springmvc依赖去掉
> > 2.查看@serverendpoint 这个类上面是否import了servlet的包
> 
> 是有HttpServletRequest ，但是后来没有用这个类，只剩下 import 没删掉，这样会有直接影响吗

只是import不会影响，但没用到的话，import也可以删掉

**Comment by poorcharlie** [comment]
> > > 1.把springmvc依赖去掉
> > > 2.查看@serverendpoint 这个类上面是否import了servlet的包
> > 
> > 
> > 是有HttpServletRequest ，但是后来没有用这个类，只剩下 import 没删掉，这样会有直接影响吗
> 
> 只是import不会影响，但没用到的话，import也可以删掉

我找到最终解决方案了，因为我的@serverendpoint 类里使用feign调用了，所以加了@RequistMapping 注解。只要在报错的类上面实现org.springframework.web.servlet.mvc.Controller 接口，就不报错了。希望Yeauty优化一下这里。

**Comment by YeautyYE** [comment]
> 我找到最终解决方案了，因为我的@serverendpoint 类里使用feign调用了，所以加了@RequistMapping 注解。只要在报错的类上面实现org.springframework.web.servlet.mvc.Controller 接口，就不报错了。希望Yeauty优化一下这里。

如果是为了暴露http方法啊，那加上@Controller应该就好了

不建议Websocket和http混在一起，因为本身不是同一个东西
