### ISSUE TITLE
经常性的出现这个问题，重连一下又正常了？[org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@26cc82c5 has been closed already]

### ISSUE THREAD

**Issue by whoooami** [YeautyYE/netty-websocket-spring-boot-starter#137]
` Completed 200 OK
2020-08-09 09:41:15.338 DEBUG 8175 --- [ntLoopGroup-5-1] i.n.h.c.h.w.WebSocketServerHandshaker    : [id: 0xf9d1696b, L:/****:10000 - R:/****:54437] WebSocket version V13 server handshake
2020-08-09 09:41:15.354 DEBUG 8175 --- [ntLoopGroup-5-1] i.n.h.c.h.w.WebSocketServerHandshaker    : WebSocket version 13 server handshake key: Dn+vtZoYi9aPHJc8VPC2oQ==, response: Bo1cjzmBeZ4VXJOGsymE5LOlB+g=
2020-08-09 09:41:15.378 ERROR 8175 --- [ntLoopGroup-5-1] org.yeauty.pojo.PojoEndpointServer       : Unexpected exception:

java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@26cc82c5 has been closed already
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1067)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1100)
        at org.yeauty.pojo.PojoMethodMapping.getEndpointInstance(PojoMethodMapping.java:249)
        at org.yeauty.pojo.PojoEndpointServer.doOnOpen(PojoEndpointServer.java:87)
        at org.yeauty.standard.HttpServerHandler.lambda$handleHttpRequest$0(HttpServerHandler.java:235)
        at org.yeauty.standard.HttpServerHandler$$Lambda$1163/1734554779.operationComplete(Unknown Source)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
        at org.yeauty.standard.HttpServerHandler.handleHttpRequest(HttpServerHandler.java:233)
        at org.yeauty.standard.HttpServerHandler.channelRead0(HttpServerHandler.java:84)
        at org.yeauty.standard.HttpServerHandler.channelRead0(HttpServerHandler.java:29)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)`

**Comment by YeautyYE** [comment]
这个估计要看看你代码在OnOpen事件中干了啥

**Comment by whoooami** [comment]
> 这个估计要看看你代码在OnOpen事件中干了啥

主要做了两件事。取出链接中的用户标识，放入缓存中。保存用户标识和Session的关系。

**Comment by YeautyYE** [comment]
> 主要做了两件事。取出链接中的用户标识，放入缓存中。保存用户标识和Session的关系。

可以看下代码吗

**Comment by whoooami** [comment]
`
@OnOpen
    public void onOpen(Session session, HttpHeaders headers, @RequestParam String req, @RequestParam MultiValueMap reqMap, @PathVariable String arg, @PathVariable Map pathMap){
        log.debug("new connection");
        log.debug(arg);
        webSocketService.addSession(arg, session);
    }
`

`
Optional<AccountIdentify> accountIdentifyOptional = getBy(arg);
integerRedisUtil.set(Constant.Cache.getCacheKey(WEBSOCKET_SESSION_ID.name(), session.id().asLongText()),
                accountIdentifyOptional.get().getUid().intValue());

        if (ValueUtil.isNotNullZero(accountIdentifyOptional.get().getUid().intValue())) {

            Constant.WebSocket.stringSessionMap.put(
                    Constant.Cache.getCacheKey(WEBSOCKET_SESSION.name(),
                            String.valueOf(accountIdentifyOptional.get().getUid())),
                    session);
            session.sendText("{\"type\":\"login\"}");
        } else {

            session.sendText("{\"type\":\"login\", \"message\":\"token is illegal.\"}");
            session.close();
        }
`

**Comment by YeautyYE** [comment]
是不是使用了spring devtool

**Comment by whoooami** [comment]
> 1.是不是使用了spring devtool
> 2.是不是spring cloud项目
> 3. webSocketService是怎么交给spring管理的，又是怎么注入进来的

1、是 2、是 3、通过@Resource 注解方式。

**Comment by YeautyYE** [comment]
建议把spring devtool先关掉试试
