### ISSUE TITLE
demo连接的上到项目中连接不上

### ISSUE THREAD

**Issue by bearmr** [YeautyYE/netty-websocket-spring-boot-starter#177]
![image](https://user-images.githubusercontent.com/10863395/114312459-56f62800-9b25-11eb-811a-2f3ae983a66a.png)

![image](https://user-images.githubusercontent.com/10863395/114312469-65444400-9b25-11eb-9b1b-c0e6e9e243ac.png)
但是进不了后台方法，demo可以但是我的api不行,想请问下作者是我哪里出了问题

**Comment by bearmr** [comment]
所有注解方法都没有进入,是否是rocketmq引起的，我还特别和mq的netty版本设置了一样也没有用,是为什么不起作用还望解答一下

**Comment by YeautyYE** [comment]
demo代码发一下

**Comment by bearmr** [comment]
我是demo 上可以但是我集成到我项目不可以






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午1:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
demo代码发一下

**Comment by YeautyYE** [comment]
项目中有报错吗？ 或者换个客户端试试

**Comment by bearmr** [comment]
项目就是没报错,但是我就是对应所有断点都进不去




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午1:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
项目中有报错吗？ 或者换个客户端试试

**Comment by YeautyYE** [comment]
那可以在chrome浏览器中用Websocket对象连连看

**Comment by bearmr** [comment]
我试试，我是使用的网页的那种在线测试,但是很奇怪的,我demo没有一点问题,但是我集成到项目中就不行,所有代码和demo中一样,是因为tomcat的原因吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午1:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
那可以在chrome浏览器中用Websocket对象连连看

**Comment by bearmr** [comment]
就是直接自己写个html来连吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午1:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
那可以在chrome浏览器中用Websocket对象连连看

**Comment by bearmr** [comment]
方便加一个微信吗,我给你远程看下问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午1:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
demo代码发一下

**Comment by bearmr** [comment]
试了不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月12日(星期一) 中午1:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
那可以在chrome浏览器中用Websocket对象连连看

**Comment by bearmr** [comment]
这是为啥我demo也是好好的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YeautyYE/netty-websocket-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月12日(星期一) 中午1:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





 
那可以在chrome浏览器中用Websocket对象连连看

**Comment by YeautyYE** [comment]
我微信:Yeauty

**Comment by Feirty** [comment]
@bearmr 你好，我遇到类似的问题，请问有解决方案吗？

**Comment by YeautyYE** [comment]
> @bearmr 你好，我遇到类似的问题，请问有解决方案吗？

通常是依赖版本冲突或环境基础设施问题，可以排查下

**Comment by bearmr** [comment]
新版本不是已经修复了吗.作者说是spring那块被拦截了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YeautyYE/netty-websocket-spring-boot-starter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月15日(星期五) 上午10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177)





  
@bearmr 你好，我遇到类似的问题，请问有解决方案吗？
  
通常是依赖版本冲突或环境基础设施问题，可以排查下
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Feirty** [comment]
> > 新版本不是已经修复了吗.作者说是spring那块被拦截了
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "YeautyYE/netty-websocket-spring-boot-starter" _**@**_._**>; 发送时间: 2021年10月15日(星期五) 上午10:57 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [YeautyYE/netty-websocket-spring-boot-starter] demo连接的上到项目中连接不上 (#177) @bearmr 你好，我遇到类似的问题，请问有解决方案吗？ 通常是依赖版本冲突或环境基础设施问题，可以排查下 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 嗯，如果是这个引起的话，已经修复了

我用的是0.12.0版本，是因为NoUniqueBeanDefinitionException异常导致的，不过这个异常并没有在控制台显示，我在源码打断点发现是抛出了NoUniqueBeanDefinitionException异常。（另起DEMO复现是可以正常显示异常）
详细异常信息：
> org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor' available: expected single matching bean but found 2: org.springframework.context.annotation.internalAutowiredAnnotationProcessor,com.alicp.jetcache.anno.field.CreateCacheAnnotationBeanPostProcessor
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1036) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:338) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:333) ~[spring-beans-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105) ~[spring-context-5.0.12.RELEASE.jar:5.0.12.RELEASE]
> 	at org.yeauty.pojo.PojoMethodMapping.getEndpointInstance(PojoMethodMapping.java:249) ~[netty-websocket-spring-boot-starter-0.12.0.jar:na]
> 	at org.yeauty.pojo.PojoEndpointServer.doOnOpen(PojoEndpointServer.java:85) ~[netty-websocket-spring-boot-starter-0.12.0.jar:na]
> 	at org.yeauty.standard.HttpServerHandler.lambda$handleHttpRequest$0(HttpServerHandler.java:249) [netty-websocket-spring-boot-starter-0.12.0.jar:na]
> 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:162) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at org.yeauty.standard.HttpServerHandler.handleHttpRequest(HttpServerHandler.java:244) [netty-websocket-spring-boot-starter-0.12.0.jar:na]
> 	at org.yeauty.standard.HttpServerHandler.channelRead0(HttpServerHandler.java:91) [netty-websocket-spring-boot-starter-0.12.0.jar:na]
> 	at org.yeauty.standard.HttpServerHandler.channelRead0(HttpServerHandler.java:31) [netty-websocket-spring-boot-starter-0.12.0.jar:na]
> 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[netty-codec-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[netty-codec-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[netty-codec-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:648) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:583) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:500) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[netty-transport-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
> 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_291]
