### ISSUE TITLE
cpu占用高

### ISSUE THREAD

**Issue by XiFYuW** [YeautyYE/netty-websocket-spring-boot-starter#189]
### 建立连接的代码：
```
@OnOpen
public void onOpen(Session session, @RequestParam String req, @PathVariable String arg){
        String key = session.id().asLongText();
        log.warn("webSocket new connection req={},arg={},id={}", req, arg, key);
        WebSocketStorage.getMapSession().putIfAbsent(session.id().asLongText(), session);
        WebSocketStorage.getListKey().add(session.id().asLongText());
}
```
### 推送信息的代码：
`mapSession.forEach((x, session) -> session.sendText(JSON.toJSONString(acnTradeSocket)));`

### 电脑配置信息：
![image](https://user-images.githubusercontent.com/33598203/119246531-f0990680-bbb4-11eb-9f4b-5270957ebf72.png)

### jvisualvm监控信息：
![image](https://user-images.githubusercontent.com/33598203/119246573-32c24800-bbb5-11eb-833d-a0de7d2bc962.png)

只有5000个连接，CPU也太高了吧

**Comment by YeautyYE** [comment]
json解析是CPU密集型。
5000连接的发送意味着发5000次，也就是解析5000次。

推送代码改成
减少json解析次数，并利用zero copy节省cpu对内存的拷贝

```java
            byte[] dataByte = JSON.toJSONString(acnTradeSocket).getBytes();
            ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer(dataByte.length).writeBytes(dataByte);
            mapSession.forEach((x, session) -> session.sendText(buf.retainedDuplicate()));
```

**Comment by XiFYuW** [comment]
![image](https://user-images.githubusercontent.com/33598203/119294215-8b154a80-bc86-11eb-8f0d-b9587de4808c.png)
cpu还是高耶

**Comment by XiFYuW** [comment]
我之前试过直接发送“1”的，cpu也挺高的。

**Comment by YeautyYE** [comment]
看上去有点奇怪，建议看看CPU高对应的线程是哪个

**Comment by XiFYuW** [comment]
那些高的，都是我发送消息时出现的。我在看看吧

**Comment by YeautyYE** [comment]
> 那些高的，都是我发送消息时出现的。我在看看吧

Windows上可以用Process Explorer先定位到占用CPU多的线程，然后再jstack把线程dump出来，找到对应的线程，看看在干啥

**Comment by XiFYuW** [comment]
**线程活动：**
![image](https://user-images.githubusercontent.com/33598203/120139663-84994c80-c20b-11eb-87bb-958db80c0a8f.png)
**4516的：**
![image](https://user-images.githubusercontent.com/33598203/120139579-53208100-c20b-11eb-89dc-bec09ed51f78.png)
**66016**
![image](https://user-images.githubusercontent.com/33598203/120139881-fffafe00-c20b-11eb-9fc1-0809095f8aa9.png)
这些看着不高，可是在jvisualvm却很高
![image](https://user-images.githubusercontent.com/33598203/120139989-2ae55200-c20c-11eb-8127-5769183fe803.png)
![image](https://user-images.githubusercontent.com/33598203/120140044-481a2080-c20c-11eb-8f96-56ad01a3ae1e.png)

**Comment by YeautyYE** [comment]
可能由于工具抓的时间间隔不够短，CPU飙升的瞬间没抓到。
可以尝试while(true)的发，看看能抓到线程不

**Comment by XiFYuW** [comment]
![image](https://user-images.githubusercontent.com/33598203/120155757-c6ce8800-c223-11eb-8dd4-eddbcdfba6c0.png)
**31992:**
```
"catalina-exec-29" #96 daemon prio=5 os_prio=0 tid=0x0000012a4b4cd000 nid=0x7cf8 runnable [0x000000138c67b000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl.setWakeupSocket0(java.base@9.0.4/Native Method)
	at sun.nio.ch.WindowsSelectorImpl.setWakeupSocket(java.base@9.0.4/WindowsSelectorImpl.java:465)
	at sun.nio.ch.WindowsSelectorImpl.wakeup(java.base@9.0.4/WindowsSelectorImpl.java:607)
	- locked <0x00000006d4939cc8> (a java.lang.Object)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.wakeup(SelectedSelectionKeySetSelector.java:73)
	at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:777)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:849)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:989)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:796)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294)
	at org.yeauty.pojo.Session.sendText(Session.java:41)
	at com.base.webSocket.WebSocketStorage.lambda$forEach$0(WebSocketStorage.java:47)
	at com.base.webSocket.WebSocketStorage$$Lambda$1156/1099400879.accept(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.forEach(java.base@9.0.4/ConcurrentHashMap.java:1617)
	at com.base.webSocket.WebSocketStorage.forEach(WebSocketStorage.java:47)
	at com.base.webSocket.WebSocketController.send(WebSocketController.java:44)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9.0.4/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9.0.4/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9.0.4/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9.0.4/Method.java:564)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x00000006d6702a70> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@9.0.4/ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@9.0.4/ThreadPoolExecutor.java:641)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(java.base@9.0.4/Thread.java:844)
```
**4172(其他的一样):**
```
"nioEventLoopGroup-9-6" #377 prio=10 os_prio=2 tid=0x0000012a4c15f000 nid=0x104c runnable [0x0000001395d7e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(java.base@9.0.4/Native Method)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(java.base@9.0.4/WindowsSelectorImpl.java:296)
	at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(java.base@9.0.4/WindowsSelectorImpl.java:278)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(java.base@9.0.4/WindowsSelectorImpl.java:159)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@9.0.4/SelectorImpl.java:86)
	- locked <0x00000006d3354848> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006d3bc1140> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006d3354768> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@9.0.4/SelectorImpl.java:97)
	at sun.nio.ch.SelectorImpl.select(java.base@9.0.4/SelectorImpl.java:101)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:803)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@9.0.4/Thread.java:844)
```
是我这个“workerLoopGroupThreads = "8"”配置的不合理吗？

**Comment by YeautyYE** [comment]
从堆栈来看，你这里是使用springmvc。通过暴露http接口，来触发发送。
但是中间经过了各种filter，不能确定是哪里慢。
你要不试一下定时群发，看看如果只有发送的话，CPU分配情况以及堆栈是怎样的

**Comment by YeautyYE** [comment]
如果可以，建议把代码贴出来

**Comment by XiFYuW** [comment]
```
while (true) {
            AcnTradeSocket acnTradeSocket = new AcnTradeSocket(
                    DateUtil.current(true),
                    new BigDecimal("123"),
                    new BigDecimal("123"),
                    0
            );
            WebSocketStorage.forEach(acnTradeSocket);
        }
```
```
byte[] dataByte = JSON.toJSONString(acnTradeSocket).getBytes();
        ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer(dataByte.length).writeBytes(dataByte);
        try {
            mapSession.forEach((x, session) -> session.sendText(buf.retainedDuplicate()));
        }finally {
            ReferenceCountUtil.release(buf);
        }
```
代码就这些

**Comment by XiFYuW** [comment]
我放redis延时队列里，一秒一个也高。

**Comment by YeautyYE** [comment]
WebSocketStorage.forEach(acnTradeSocket); 
和下面那段代码是什么关系

**Comment by XiFYuW** [comment]
调用

**Comment by XiFYuW** [comment]
public static void forEach(AcnTradeSocket acnTradeSocket){
        log.warn("webSocket 处理：{}", acnTradeSocket.toString());
        byte[] dataByte = JSON.toJSONString(acnTradeSocket).getBytes();
        ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer(dataByte.length).writeBytes(dataByte);
        try {
            mapSession.forEach((x, session) -> session.sendText(buf.retainedDuplicate()));
        }finally {
            ReferenceCountUtil.release(buf);
        }
    }

**Comment by YeautyYE** [comment]
代码看上去没问题。
看下cpu峰值会持续多久，如果只是一瞬间，那可以忽略

**Comment by XiFYuW** [comment]
不，一直都高....

**Comment by XiFYuW** [comment]
![image](https://user-images.githubusercontent.com/33598203/120162846-66434900-c22b-11eb-8f5e-a4d9da44f464.png)

**Comment by XiFYuW** [comment]
![image](https://user-images.githubusercontent.com/33598203/120163124-bf12e180-c22b-11eb-9104-675ac571dcf6.png)

**Comment by XiFYuW** [comment]
![image](https://user-images.githubusercontent.com/33598203/120163812-7dcf0180-c22c-11eb-9bb1-b481ad711e43.png)

**Comment by YeautyYE** [comment]
是一次群发持续那么久吗？

**Comment by XiFYuW** [comment]
群发很快，但cpu很高。
![image](https://user-images.githubusercontent.com/33598203/120164564-4dd42e00-c22d-11eb-9028-bdc6f1686bb4.png)
这个时间段都是在循环发送。

**Comment by XiFYuW** [comment]
发送的时上下文切换最高有43000左右

**Comment by XiFYuW** [comment]
![image](https://user-images.githubusercontent.com/33598203/120165160-dc48af80-c22d-11eb-9be4-bdb78d4972c0.png)

**Comment by YeautyYE** [comment]
看线程数和进程数应该是整个主机的，而不是这个进程的。
CPU应该也是整个主机的。而且调用发送正是是存在上下文切换的，属于正常现象
可以看下群发5000的时候，峰值会维持多久，如果只是一瞬间的话是正常的

**Comment by XiFYuW** [comment]
4核的：群发5000一直发，cpu就一直是满的。其实只要群发5000cpu就会升高。
8核cpu是正常的。

**Comment by YeautyYE** [comment]
> 4核的：群发5000一直发，cpu就一直是满的。其实只要群发5000cpu就会升高。
> 8核cpu是正常的。

这个听上去像是CPU不够强。
不过足够快的话就没问题

**Comment by pengyongjianpyj** [comment]
> 4核的：群发5000一直发，cpu就一直是满的。其实只要群发5000cpu就会升高。
> 8核cpu是正常的。

我压测过25000左右的并发，使用的服务器是16核64g的。
当时监控资源占用cpu和内存都只占用了1%。
