### ISSUE TITLE
关于服务重启

### ISSUE THREAD

**Issue by hlwskgypmb** [YeautyYE/netty-websocket-spring-boot-starter#195]
怎么样在服务重启前关闭所有的socket链接呢 怎么能通过onClose方法，需要清空redis对应的连接数据

java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.yeauty.pojo.PojoEndpointServer.doOnClose(PojoEndpointServer.java:125) ~[netty-websocket-spring-boot-starter-0.11.0.jar:na]
	at org.yeauty.standard.WebSocketServerHandler.channelInactive(WebSocketServerHandler.java:29) [netty-websocket-spring-boot-starter-0.11.0.jar:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$300(AbstractChannelHandlerContext.java:38) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.channel.AbstractChannelHandlerContext$4.run(AbstractChannelHandlerContext.java:236) [netty-transport-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.29.Final.jar:4.1.29.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
Caused by: java.lang.IllegalStateException: Cannot connect, Event executor group is terminated.
	at io.lettuce.core.AbstractRedisClient.initializeChannelAsync(AbstractRedisClient.java:254) ~[lettuce-core-5.0.5.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:318) ~[lettuce-core-5.0.5.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:276) ~[lettuce-core-5.0.5.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connectStandalone(RedisClient.java:252) ~[lettuce-core-5.0.5.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.connect(RedisClient.java:202) ~[lettuce-core-5.0.5.RELEASE.jar:na]
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:56) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:959) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:934) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:786) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:300) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:132) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:95) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.core.RedisConnectionUtils.getConnection(RedisConnectionUtils.java:82) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:211) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171) ~[spring-data-redis-2.0.11.RELEASE.jar:2.0.11.RELEASE]
	at com.pt.device.framework.utils.RedisUtil.delKey(RedisUtil.java:592) ~[classes/:na]
	at com.pt.device.config.WsSessionManager.remove(WsSessionManager.java:87) ~[classes/:na]
	at com.pt.device.handler.DeviceHandler.onClose(DeviceHandler.java:88) ~[classes/:na]
	... 13 common frames omitted

Process finished with exit code 130

**Comment by hlwskgypmb** [comment]
应该是redis关闭太早，onClose时候资源已释放
