### ISSUE TITLE
.

### ISSUE THREAD

**Issue by tanzheng231** [YeautyYE/netty-websocket-spring-boot-starter#50]
-

**Comment by YeautyYE** [comment]
请问内存泄漏问题在哪

**Comment by shuaiyinoo** [comment]
有内存泄漏
```
Exception in thread "http-nio-9211-exec-338" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-nio-9211-exec-333" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-332" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-311" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "http-nio-9211-exec-26" Exception in thread "http-nio-9211-exec-14" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

现在600个手机一次性全部链接上了 就全挂了

**Comment by shuaiyinoo** [comment]
现在是连 启动都启动不了了不知道为啥错误日志也没有

**Comment by shuaiyinoo** [comment]
```
32620 --- [ntLoopGroup-5-2] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by org.yeauty.standard.HttpServerHandler$$Lambda$761/1132740528.operationComplete()
java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-ClientPoller-1" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "http-nio-9211-ClientPoller-1"
```

**Comment by tanzheng231** [comment]
应该是你分配的堆内存小了 ,加大试试

**Comment by YeautyYE** [comment]
> 有内存泄漏
> 
> ```
> Exception in thread "http-nio-9211-exec-338" java.lang.OutOfMemoryError: GC overhead limit exceeded
> Exception in thread "http-nio-9211-exec-333" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-332" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-311" java.lang.OutOfMemoryError: GC overhead limit exceeded
> Exception in thread "http-nio-9211-exec-26" Exception in thread "http-nio-9211-exec-14" java.lang.OutOfMemoryError: GC overhead limit exceeded
> ```
> 
> 现在600个手机一次性全部链接上了 就全挂了

首先，内存泄漏和内存溢出是两个不同的事情。
在Java中如果使用堆内存，那一般是内存溢出。如果使用了堆外内存，并且自己没管理好，那就会导致内存泄漏(使用堆外内存只能自己管理)
从几个点开始排查
1.600个手机连接上去，如果什么都没做，理论上是空连接，是不会发生内存溢出的。
2.如果是启动都无法启动，需要判断服务器资源是否本身就不足。
3.如果使用到堆外内存，记得自己去释放掉。

**Comment by shuaiyinoo** [comment]
现在启动的时候 加大了 一样启动不起来了 应该是有一个BUG了
java -jar -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms2048m -Xmx2048m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC pis.jar

**Comment by YeautyYE** [comment]
> 现在启动的时候 加大了 一样启动不起来了 应该是有一个BUG了
> java -jar -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms2048m -Xmx2048m -Xmn256m -Xss256k -XX:SurvivorRatio=8 -XX:+UseConcMarkSweepGC pis.jar

如果是启动不起来，你需要查看，你的启动参数是否比服务器所剩的资源更大。
如：一台1核1G的服务器上要带 -Xms1g -Xmx1g ，显然是有问题的

**Comment by shuaiyinoo** [comment]
是启动起来后 报错 不是启动之前报错 如果Nginx的流量接进来就报错

**Comment by shuaiyinoo** [comment]
```
121" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-124" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-120" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-78" java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
        at org.apache.coyote.http11.Http11OutputBuffer.<init>(Http11OutputBuffer.java:106)
        at org.apache.coyote.http11.Http11Processor.<init>(Http11Processor.java:159)
        at org.apache.coyote.http11.AbstractHttp11Protocol.createProcessor(AbstractHttp11Protocol.java:940)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:824)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-123" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-118" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-122" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
        at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
        at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
        at org.apache.coyote.http11.Http11OutputBuffer.<init>(Http11OutputBuffer.java:106)
        at org.apache.coyote.http11.Http11Processor.<init>(Http11Processor.java:159)
        at org.apache.coyote.http11.AbstractHttp11Protocol.createProcessor(AbstractHttp11Protocol.java:940)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:824)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "http-nio-9211-exec-101" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-98" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-100" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-112" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-113" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-114" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-115" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-9211-exec-116" java.lang.OutOfMemoryError: Java heap s
```

**Comment by shuaiyinoo** [comment]
现在是不带也报错了

**Comment by YeautyYE** [comment]
> 是启动起来后 报错 不是启动之前报错 如果Nginx的流量接进来就报错



> ```
> 121" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-124" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-120" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-78" java.lang.OutOfMemoryError: Java heap space
>         at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
>         at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
>         at org.apache.coyote.http11.Http11OutputBuffer.<init>(Http11OutputBuffer.java:106)
>         at org.apache.coyote.http11.Http11Processor.<init>(Http11Processor.java:159)
>         at org.apache.coyote.http11.AbstractHttp11Protocol.createProcessor(AbstractHttp11Protocol.java:940)
>         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:824)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
>         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.lang.Thread.run(Thread.java:748)
> java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-123" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-118" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-122" java.lang.OutOfMemoryError: Java heap space
> java.lang.OutOfMemoryError: Java heap space
>         at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
>         at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
>         at org.apache.coyote.http11.Http11OutputBuffer.<init>(Http11OutputBuffer.java:106)
>         at org.apache.coyote.http11.Http11Processor.<init>(Http11Processor.java:159)
>         at org.apache.coyote.http11.AbstractHttp11Protocol.createProcessor(AbstractHttp11Protocol.java:940)
>         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:824)
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
>         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>         at java.lang.Thread.run(Thread.java:748)
> Exception in thread "http-nio-9211-exec-101" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-98" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-100" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-112" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-113" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-114" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-115" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "http-nio-9211-exec-116" java.lang.OutOfMemoryError: Java heap s
> ```

从这里可以看出，你报出OOM的是tomcat，而不是本框架(本框架用的是Netty)
2种排查方式
1.通过jmap把内存dump出来通过MAT分析
2.可以尝试把你的业务代码全部去掉，排查空连接是否有问题

**Comment by shuaiyinoo** [comment]
可能是很多东西一起 然后都崩了 全部报错了 我再看看

**Comment by shuaiyinoo** [comment]
好了 我升级了服务器 从8G升级到了16G 然后把MySQL进行了优化 
原因 MySQL占用了所有CPU 导致文件上传服务挂了 然后手机端每秒报送大文件 导致内存溢出 Nginx没有限流 现在优化MySQL后 这个问题解决了 服务没有拆分 一挂全挂了

**Comment by YeautyYE** [comment]
> 好了 我升级了服务器 从8G升级到了16G 然后把MySQL进行了优化
> 原因 MySQL占用了所有CPU 导致文件上传服务挂了 然后手机端每秒报送大文件 导致内存溢出 Nginx没有限流 现在优化MySQL后 这个问题解决了 服务没有拆分 一挂全挂了

好的。

**Comment by shuaiyinoo** [comment]
有 多个Spring Boot 共享Session方案么 我怎么共享所有的链接到别的java进程中 如果我启动多个做负载均衡的话 这个好像没有找到门道 对WSS 跟HTTPS的 我们套了一层Nginx解决了 YeautyYE

**Comment by YeautyYE** [comment]
> 有 多个Spring Boot 共享Session方案么 我怎么共享所有的链接到别的java进程中 如果我启动多个做负载均衡的话 这个好像没有找到门道 对WSS 跟HTTPS的 我们套了一层Nginx解决了 YeautyYE

由于websocket中session和普通的http请求中的session本质上不是一个东西，所以并不能像http一样直接将session信息存起来共享。如果需要做到分布式，简单的思路就是需要有个集中式的地方，知道每个session在具体哪个服务器上。然后通过远程调用/通知去让服务器推送消息。下面是一种简单的解决方案
需要:
redis(memcached) 用来存client唯一标示(如:userId) 和server唯一标示(如: ip)
kafka(rocketmq、rabbitmq) 用于异步通知相应的server发送消息
流程:
1.当client连接时,在redis中存入userId:serverIp,并在当前应用的一个map中添加userId和对应的session
2.当需要对某client发送消息时,先去redis中查出对应的serverIp,通过kafka推送一条消息(topic:serverIp key:userId value:content)
3.当对应的server收到消息时,找到 第 1 步中的map ,把相应的session获取到,调用sendText()方法发送消息
4.当client关闭连接时,把redis中相应的记录删除
tips1:以上是主要的流程,没有提到如server挂掉时,如何把redis中的记录删除,其实有很多解决方案,如加上过期时间 .
tips2:建议通过装饰者模式,将session和上面的部分流程集成起来,以后的调用者会更加的舒服

**Comment by shuaiyinoo** [comment]
这里有个空指针

`java.lang.reflect.InvocationTargetException: null
        at sun.reflect.GeneratedMethodAccessor312.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
        at org.yeauty.pojo.PojoEndpointServer.doOnMessage(PojoEndpointServer.java:180) ~[netty-websocket-spring-boot-starter-0.8.0.jar!/:na]
        at org.yeauty.standard.WebSocketServerHandler.handleWebSocketFrame(WebSocketServerHandler.java:39) [netty-websocket-spring-boot-starter-0.8.0.jar!/:na]
        at org.yeauty.standard.WebSocketServerHandler.channelRead0(WebSocketServerHandler.java:19) [netty-websocket-spring-boot-starter-0.8.0.jar!/:na]
        at org.yeauty.standard.WebSocketServerHandler.channelRead0(WebSocketServerHandler.java:9) [netty-websocket-spring-boot-starter-0.8.0.jar!/:na]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) [netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) [netty-codec-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar!/:4.1.36.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.36.Final.jar!/:4.1.36.Final]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.lang.NullPointerException: null`
