### ISSUE TITLE
连接数过多时出现nioEventLoop该如何限制

### ISSUE THREAD

**Issue by zerolbsony** [YeautyYE/netty-websocket-spring-boot-starter#84]
因为cpu负载很高，且虚拟内存占用量也很高，通过jstack 进程，发现大量的如下操作，且造成了其它线程的等待，怀疑是连接数过多导致：

top - 10:31:15 up 261 days,  2:46,  1 user,  load average: 0.94, 1.45, 1.66
Tasks: 199 total,   1 running, 198 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.3 us,  1.6 sy,  0.0 ni, 91.9 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
KiB Mem : 32779908 total, 12644272 free,  8373568 used, 11762068 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 23807716 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                            
 2743 root      20   0 23.872g 1.387g  14016 S 126.2  4.4  19192:52 java      

"nioEventLoopGroup-3-25" #4502 prio=10 os_prio=0 tid=0x00007f6454063000 nid=0x2e73 runnable [0x00007f62ebdfc000]
java.lang.Thread.State: RUNNABLE
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000e13c4420> (a java.util.concurrent.locks.AbstractQueuedSynchronizerConditionObject)atjava.util.concurrent.locks.LockSupport.park(LockSupport.java:175)atjava.util.concurrent.locks.AbstractQueuedSynchronizerConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.ScheduledThreadPoolExecutorDelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)atjava.util.concurrent.ScheduledThreadPoolExecutorDelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

"pushMsg-schedule-pool-1" #4504 daemon prio=5 os_prio=0 tid=0x00007f646c0b8800 nid=0x2e7b waiting on condition [0x00007f62eb5f4000]
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x00000000e13c4420> (a java.util.concurrent.locks.AbstractQueuedSynchronizerConditionObject)atjava.util.concurrent.locks.LockSupport.park(LockSupport.java:175)atjava.util.concurrent.locks.AbstractQueuedSynchronizerConditionObject.await(AbstractQueuedSynchronizer.java:2039)
at java.util.concurrent.ScheduledThreadPoolExecutorDelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)atjava.util.concurrent.ScheduledThreadPoolExecutorDelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

"nioEventLoopGroup-3-26" #4503 prio=10 os_prio=0 tid=0x00007f6454063800 nid=0x2e7a runnable [0x00007f6321ded000]
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
- locked <0x00000000e05e62c0> (a io.netty.channel.nio.SelectedSelectionKeySet)
- locked <0x00000000e05e73c0> (a java.util.CollectionsUnmodifiableSet)−locked<0x00000000e05e72e8>(asun.nio.ch.EPollSelectorImpl)atsun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)atio.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)atio.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)atio.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)atio.netty.util.concurrent.SingleThreadEventExecutor5.run(SingleThreadEventExecutor.java:884)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

**Comment by YeautyYE** [comment]
CPU 6%，不算高。
而且连接数过高也不会导致负载高。
nioEventLoop也不能用来限制连接数。

**Comment by zerolbsony** [comment]
> CPU 6%，不算高。
> 而且连接数过高也不会导致负载高。
> nioEventLoop也不能用来限制连接数。

cpu 经常190%，虚拟内存28G，这个还不严重？

**Comment by YeautyYE** [comment]
> > CPU 6%，不算高。
> > 而且连接数过高也不会导致负载高。
> > nioEventLoop也不能用来限制连接数。
> 
> cpu 经常190%，虚拟内存28G，这个还不严重？

建议你先通过top把最耗CPU的线程找出来再去jstack。
因为连接数过高通常不会导致CPU飙升

**Comment by YeautyYE** [comment]
> > CPU 6%，不算高。
> > 而且连接数过高也不会导致负载高。
> > nioEventLoop也不能用来限制连接数。
> 
> cpu 经常190%，虚拟内存28G，这个还不严重？

对于内存，你可以jmap去查。
连接是不怎么占内存的。

**Comment by zerolbsony** [comment]
> > > CPU 6%，不算高。
> > > 而且连接数过高也不会导致负载高。
> > > nioEventLoop也不能用来限制连接数。
> > 
> > 
> > cpu 经常190%，虚拟内存28G，这个还不严重？
> 
> 对于内存，你可以jmap去查。
> 连接是不怎么占内存的。

可以加个联系方式，协助我解决一下这个问题吗
