### ISSUE TITLE
启动报错怎么回事啊

### ISSUE THREAD

**Issue by xieende** [YeautyYE/netty-websocket-spring-boot-starter#90]
2020-01-05 19:46:15.786 ERROR 6256 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to register ServerEndpointConfig: org.yeauty.standard.ServerEndpointConfig@174682a9
	at org.yeauty.standard.ServerEndpointExporter.registerEndpoint(ServerEndpointExporter.java:78) ~[netty-websocket-spring-boot-starter-0.8.0.jar:na]
	at org.yeauty.standard.ServerEndpointExporter.registerEndpoints(ServerEndpointExporter.java:49) ~[netty-websocket-spring-boot-starter-0.8.0.jar:na]
	at org.yeauty.standard.ServerEndpointExporter.afterSingletonsInstantiated(ServerEndpointExporter.java:34) ~[netty-websocket-spring-boot-starter-0.8.0.jar:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:777) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.un.net.UnNetApplication.main(UnNetApplication.java:10) [classes/:na]

按照博客来的，然后启动application ，就报错了，咋回事啊，起不来

**Comment by YeautyYE** [comment]
> 2020-01-05 19:46:15.786 ERROR 6256 --- [ restartedMain] o.s.boot.SpringApplication : Application run failed
> 
> java.lang.IllegalStateException: Failed to register ServerEndpointConfig: org.yeauty.standard.ServerEndpointConfig@174682a9
> at org.yeauty.standard.ServerEndpointExporter.registerEndpoint(ServerEndpointExporter.java:78) ~[netty-websocket-spring-boot-starter-0.8.0.jar:na]
> at org.yeauty.standard.ServerEndpointExporter.registerEndpoints(ServerEndpointExporter.java:49) ~[netty-websocket-spring-boot-starter-0.8.0.jar:na]
> at org.yeauty.standard.ServerEndpointExporter.afterSingletonsInstantiated(ServerEndpointExporter.java:34) ~[netty-websocket-spring-boot-starter-0.8.0.jar:na]
> at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:777) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
> at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
> at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
> at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
> at com.un.net.UnNetApplication.main(UnNetApplication.java:10) [classes/:na]
> 
> 按照博客来的，然后启动application ，就报错了，咋回事啊，起不来

应该还有个 DeploymentException 。 你看下完整的报错信息

**Comment by zhoulibo1988** [comment]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-12-18 11:08:40.233 ERROR 9460 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to register ServerEndpointConfig: org.yeauty.standard.ServerEndpointConfig@475646d4
	at org.yeauty.standard.ServerEndpointExporter.registerEndpoint(ServerEndpointExporter.java:96) ~[netty-websocket-spring-boot-starter-0.9.5.jar:na]
	at org.yeauty.standard.ServerEndpointExporter.registerEndpoints(ServerEndpointExporter.java:63) ~[netty-websocket-spring-boot-starter-0.9.5.jar:na]
	at org.yeauty.standard.ServerEndpointExporter.afterSingletonsInstantiated(ServerEndpointExporter.java:39) ~[netty-websocket-spring-boot-starter-0.9.5.jar:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:910) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.chigua.springboot.SpringbootStudyWebsocketApplication.main(SpringbootStudyWebsocketApplication.java:18) [classes/:na]
Caused by: org.yeauty.exception.DeploymentException: pojoMethodMapping.paramClassIncorrect parameter name : parameterMap
	at org.yeauty.pojo.PojoMethodMapping.getResolvers(PojoMethodMapping.java:337) ~[netty-websocket-spring-boot-starter-0.9.5.jar:na]
	at org.yeauty.pojo.PojoMethodMapping.<init>(PojoMethodMapping.java:216) ~[netty-websocket-spring-boot-starter-0.9.5.jar:na]
	at org.yeauty.standard.ServerEndpointExporter.registerEndpoint(ServerEndpointExporter.java:94) ~[netty-websocket-spring-boot-starter-0.9.5.jar:na]
	... 13 common frames omitted

2020-12-18 11:08:40.237  INFO 9460 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
Disconnected from the target VM, address: '127.0.0.1:51269', transport: 'socket'

Process finished with exit code 1




作者 请问下 是怎么了这个

**Comment by YeautyYE** [comment]
paramClassIncorrect parameter name : parameterMap
类导包错了

**Comment by zhoulibo1988** [comment]
我框架使用了 spring-security auth2.0 安全框架 在集成了作者的jar后，websocket连接成功，但是进不了@BeforeHandshake
    public void handshake(Session session, HttpHeaders headers, @RequestParam String req, @RequestParam MultiValueMap reqMap, @PathVariable String arg, @PathVariable Map pathMap){
        session.setSubprotocols("stomp");
        if (!"ok".equals(req)){
            System.out.println("Authentication failed!");
            session.close();
        }
    }
这个方法，没有报任何错误，感觉好像被拦截了一样，请问怎么解决，
![image](https://user-images.githubusercontent.com/26712945/102574777-9048f900-412c-11eb-8deb-b62ff6a03dd5.png)

**Comment by YeautyYE** [comment]
导错包了吧，看下import是否org.yeauty开头的，有没有哪个注解不是的
